"""Protocol and DailyContract models."""

from datetime import datetime, date
from decimal import Decimal
from uuid import UUID

from sqlalchemy import DateTime, Date, String, Numeric, ForeignKey, func, Integer
from sqlalchemy.dialects.postgresql import UUID as PG_UUID, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.db.base import Base


class Protocol(Base):
    """Health protocol generated by agent consensus."""
    __tablename__ = "protocols"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("agent_sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20),
        default="draft",
        nullable=False,
    )  # draft, approved, active, archived
    nutrition_plan: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    supplement_plan: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    fitness_plan: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    sleep_protocol: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    environment: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    medical_actions: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    valid_from: Mapped[date | None] = mapped_column(Date, nullable=True)
    valid_until: Mapped[date | None] = mapped_column(Date, nullable=True)
    approved_by: Mapped[str | None] = mapped_column(String(50), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="protocols",
    )
    session: Mapped["AgentSession | None"] = relationship(
        "AgentSession",
        back_populates="protocols",
    )
    daily_contracts: Mapped[list["DailyContract"]] = relationship(
        "DailyContract",
        back_populates="protocol",
        cascade="all, delete-orphan",
    )


class DailyContract(Base):
    """Daily health tasks derived from protocol."""
    __tablename__ = "daily_contracts"

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    user_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    protocol_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("protocols.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    contracts: Mapped[dict] = mapped_column(JSON, nullable=False)
    completion_rate: Mapped[Decimal] = mapped_column(Numeric(3, 2), default=0, nullable=False)
    longevity_delta: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="daily_contracts",
    )
    protocol: Mapped["Protocol"] = relationship(
        "Protocol",
        back_populates="daily_contracts",
    )
