"""Daily contracts (actionable items) endpoints."""

from datetime import date, datetime, timedelta
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.deps import get_current_user, get_db
from src.api.schemas.protocol import ContractResponse

router = APIRouter(prefix="/contracts", tags=["Contracts"])


@router.get("/today", response_model=ContractResponse)
async def get_today_contracts(
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> ContractResponse:
    """Get today's contracts for the current user.

    Retrieve daily health commitments (contracts) for today with current
    completion status. Contracts are generated by agent pipeline recommendations.

    Args:
        db: Database session
        current_user: Current authenticated user

    Returns:
        ContractResponse: Today's contracts with completion status and impact
    """
    user_id = current_user["id"]
    today = date.today()

    # TODO: Query contracts from DB for today
    # Implementation should:
    # - Filter by user_id and date = today
    # - Populate contracts list with ContractItem objects
    # - Calculate completion_rate (completed / total)
    # - Calculate longevity_delta based on completed contracts

    return ContractResponse(
        id=UUID(int=0),
        date=today,
        contracts=[],
        completion_rate=0.0,
        longevity_delta=None,
    )


@router.get("/{target_date}", response_model=ContractResponse)
async def get_contracts_for_date(
    target_date: date,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> ContractResponse:
    """Get contracts for a specific date.

    Retrieve health contracts (daily commitments) for any date in history
    or future. Useful for tracking past adherence or viewing planned commitments.

    Args:
        target_date: Target date in format YYYY-MM-DD
        db: Database session
        current_user: Current authenticated user

    Returns:
        ContractResponse: Contracts for the specified date

    Raises:
        HTTPException: 404 if no contracts found for date
    """
    user_id = current_user["id"]

    # TODO: Query contracts from DB for specific date
    # Implementation should:
    # - Filter by user_id and date = target_date
    # - Return empty contracts list if none exist (don't 404)
    # - Populate contracts and calculate completion_rate

    return ContractResponse(
        id=UUID(int=0),
        date=target_date,
        contracts=[],
        completion_rate=0.0,
        longevity_delta=None,
    )


@router.patch("/{contract_id}/complete", response_model=dict, status_code=status.HTTP_200_OK)
async def mark_contract_complete(
    contract_id: UUID,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> dict:
    """Mark a contract as completed.

    Record user completion of a health contract item. Updates contract status
    and triggers longevity score recalculation.

    Args:
        contract_id: UUID of the contract
        db: Database session
        current_user: Current authenticated user

    Returns:
        dict: Updated contract status with longevity impact

    Raises:
        HTTPException: 404 if contract not found
        HTTPException: 403 if contract doesn't belong to current user
    """
    # TODO: Update contract completion in DB
    # Implementation should:
    # - Query contract where id = contract_id and user_id = current_user["id"]
    # - Raise 404 if not found
    # - Set completed = True and completed_at = now
    # - Calculate longevity_impact based on impact_score
    # - Update parent daily_contract.completion_rate

    return {
        "contract_id": str(contract_id),
        "completed": True,
        "completed_at": datetime.utcnow().isoformat(),
        "longevity_impact": 0.0,
        "message": "Contract marked as completed",
    }


@router.get("/history", response_model=dict)
async def get_contract_history(
    start_date: date | None = None,
    end_date: date | None = None,
    skip: int = 0,
    limit: int = 100,
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(get_current_user),
) -> dict:
    """Get contract completion history with statistics.

    Retrieve historical contract data with completion rates, trends,
    and longevity impact analysis over time.

    Args:
        start_date: Optional start date (default: 90 days ago)
        end_date: Optional end date (default: today)
        skip: Number of records to skip (pagination)
        limit: Maximum records to return (default 100)
        db: Database session
        current_user: Current authenticated user

    Returns:
        dict: Historical contract data with completion stats and trends
    """
    user_id = current_user["id"]

    if start_date is None:
        start_date = date.today() - timedelta(days=90)
    if end_date is None:
        end_date = date.today()

    # TODO: Query contract history from DB
    # Implementation should:
    # - Filter by user_id and date range
    # - Group by date to get daily completion_rate
    # - Calculate aggregate stats (avg_completion_rate, total_impact, etc.)
    # - Apply pagination
    # - Return daily_data list with {date, completion_rate, longevity_delta}

    return {
        "user_id": user_id,
        "period": {
            "start": start_date.isoformat(),
            "end": end_date.isoformat(),
        },
        "statistics": {
            "average_completion_rate": 0.0,
            "total_days": 0,
            "days_completed": 0,
            "total_longevity_impact": 0.0,
        },
        "daily_data": [],
        "trend": None,
    }
